import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../../../domain/models/protocols/reminder_config.dart';
import '../../../data/repositories/protocols/reminder_config_repository_impl.dart';

part 'reminder_config_provider.g.dart';

// ============================================================================
// REMINDER CONFIG DATA PROVIDER
// ============================================================================

/// Main reminder config provider - manages all reminder configurations
///
/// Reminder configurations control when and how notifications are sent for
/// upcoming care events (vaccinations, deworming, appointments, medications).
///
/// Usage:
/// ```dart
/// final configs = await ref.read(reminderConfigsProvider.future);
/// ```
@riverpod
class ReminderConfigs extends _$ReminderConfigs {
  @override
  Future<List<ReminderConfig>> build() async {
    final repository = ref.watch(reminderConfigRepositoryProvider);
    return await repository.getAll();
  }

  /// Save a reminder configuration (create or update)
  ///
  /// After saving, this will reschedule all notifications for the affected pet/event type.
  Future<void> saveConfig(ReminderConfig config) async {
    final repository = ref.read(reminderConfigRepositoryProvider);
    await repository.save(config);

    // Reschedule notifications with new config
    // TODO: Implement notification rescheduling via ReminderSchedulerService
    // final reminderService = ref.read(reminderSchedulerServiceProvider);
    // await reminderService.rescheduleForPet(config.petId, config.eventType);

    ref.invalidateSelf();
  }

  /// Delete a reminder configuration
  ///
  /// This will also cancel any scheduled notifications for this configuration.
  Future<void> deleteConfig(String id) async {
    final repository = ref.read(reminderConfigRepositoryProvider);

    // Get config before deleting to cancel notifications
    final config = await repository.getById(id);
    if (config != null) {
      // TODO: Cancel notifications for this config
      // final reminderService = ref.read(reminderSchedulerServiceProvider);
      // await reminderService.cancelForPet(config.petId, config.eventType);
    }

    await repository.delete(id);
    ref.invalidateSelf();
  }

  /// Get or create a default reminder configuration for a pet/event type
  ///
  /// If a configuration doesn't exist, creates one with smart defaults:
  /// - Reminder offsets: [1, 7, 14] days before event
  /// - Enabled by default
  ///
  /// Usage:
  /// ```dart
  /// final config = await ref.read(reminderConfigsProvider.notifier).getOrCreateDefault(
  ///   petId: 'pet-123',
  ///   eventType: 'vaccination',
  /// );
  /// ```
  Future<ReminderConfig> getOrCreateDefault({
    required String petId,
    required String eventType,
  }) async {
    final repository = ref.read(reminderConfigRepositoryProvider);
    final existing = await repository.getByPetIdAndEventType(petId, eventType);

    if (existing.isNotEmpty) return existing.first;

    // Create default config: reminders at 1, 7, and 14 days before
    final defaultConfig = ReminderConfig(
      id: '', // Will be generated by repository
      petId: petId,
      eventType: eventType,
      reminderDays: [1, 7, 14],
      isEnabled: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await repository.save(defaultConfig);
    ref.invalidateSelf();
    return defaultConfig;
  }

  /// Bulk update reminder offsets for a pet/event type
  ///
  /// Convenience method to update just the offset days while preserving other settings.
  Future<void> updateOffsets({
    required String petId,
    required String eventType,
    required List<int> offsetDays,
  }) async {
    final config = await getOrCreateDefault(petId: petId, eventType: eventType);
    final updated = config.copyWith(
      reminderDays: offsetDays,
      updatedAt: DateTime.now(),
    );
    await saveConfig(updated);
  }

  /// Toggle enabled status for a reminder configuration
  Future<void> toggleEnabled(String id) async {
    final repository = ref.read(reminderConfigRepositoryProvider);
    final config = await repository.getById(id);
    if (config == null) {
      throw ArgumentError('Reminder config with ID $id not found');
    }

    final updated = config.copyWith(
      isEnabled: !config.isEnabled,
      updatedAt: DateTime.now(),
    );
    await saveConfig(updated);
  }
}

// ============================================================================
// FILTERED REMINDER CONFIG PROVIDERS
// ============================================================================

/// Get reminder configuration for a specific pet and event type
///
/// Returns null if no configuration exists. Use `getOrCreateDefault` on the
/// main provider to get or create a default configuration.
///
/// Usage:
/// ```dart
/// final config = await ref.read(reminderConfigByPetIdAndEventTypeProvider(
///   petId: 'pet-123',
///   eventType: 'vaccination',
/// ).future);
/// ```
@riverpod
Future<ReminderConfig?> reminderConfigByPetIdAndEventType(
  ReminderConfigByPetIdAndEventTypeRef ref, {
  required String petId,
  required String eventType,
}) async {
  final repository = ref.watch(reminderConfigRepositoryProvider);
  final configs = await repository.getByPetIdAndEventType(petId, eventType);
  return configs.isNotEmpty ? configs.first : null;
}

/// Get all reminder configurations for a specific event type
///
/// Usage:
/// ```dart
/// final vaccinationConfigs = await ref.read(
///   reminderConfigsByEventTypeProvider('vaccination').future
/// );
/// ```
@riverpod
Future<List<ReminderConfig>> reminderConfigsByEventType(
  ReminderConfigsByEventTypeRef ref,
  String eventType,
) async {
  final repository = ref.watch(reminderConfigRepositoryProvider);
  return await repository.getByEventType(eventType);
}

/// Get all reminder configurations for a specific pet
///
/// Usage:
/// ```dart
/// final petConfigs = await ref.read(
///   reminderConfigsByPetIdProvider('pet-123').future
/// );
/// ```
@riverpod
Future<List<ReminderConfig>> reminderConfigsByPetId(
  ReminderConfigsByPetIdRef ref,
  String petId,
) async {
  final repository = ref.watch(reminderConfigRepositoryProvider);
  return await repository.getByPetId(petId);
}

/// Get a specific reminder configuration by ID
///
/// Returns null if configuration not found.
///
/// Usage:
/// ```dart
/// final config = await ref.read(reminderConfigByIdProvider('config-id').future);
/// ```
@riverpod
Future<ReminderConfig?> reminderConfigById(
  ReminderConfigByIdRef ref,
  String id,
) async {
  final repository = ref.watch(reminderConfigRepositoryProvider);
  return await repository.getById(id);
}

/// Get default reminder offsets based on event type
///
/// Provides sensible defaults for different event types:
/// - Vaccinations: [1, 7, 14] days before
/// - Deworming: [1, 7, 14] days before
/// - Appointments: [1, 3, 7] days before (more urgent)
/// - Medications: [1, 3] days before (most urgent)
///
/// Usage:
/// ```dart
/// final offsets = ref.read(defaultReminderOffsetsProvider('vaccination'));
/// ```
@riverpod
List<int> defaultReminderOffsets(
  DefaultReminderOffsetsRef ref,
  String eventType,
) {
  switch (eventType.toLowerCase()) {
    case 'appointment':
      return [1, 3, 7];
    case 'medication':
      return [1, 3];
    case 'vaccination':
    case 'deworming':
    default:
      return [1, 7, 14];
  }
}
